lexik_jwt_authentication:
  secret_key: "%kernel.project_dir%/config/jwt/private.pem" # required for token creation
  #secret_key: "%env(JWT_PRIVATE_KEY)%" # required for token creation
  public_key: "%kernel.project_dir%/config/jwt/public.pem" # required for token verification
  #public_key: "%env(JWT_PUBLIC_KEY)%" # required for token creation
  pass_phrase: "test" # required for token creation, usage of an environment variable is recommended
  token_ttl: 2419200 #4 semaines
